global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # MEV Shield Core Service
  - job_name: 'mev-shield-core'
    static_configs:
      - targets: ['mev-shield-core:9090']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (if needed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 15s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []